name: Python Package using pip

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install pip and project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python scripts
      run: |
        if [ -f app.py ]; then python app.py; fi
        if [ -f dashboard.py ]; then python dashboard.py; fi
        if [ -f analysis.py ]; then python analysis.py; fi

    - name: Install Jupyter tools
      run: pip install nbconvert ipykernel

    - name: Execute Jupyter Notebooks
      run: |
        for nb in *.ipynb; do
          jupyter nbconvert --to notebook --execute "$nb" --output "executed_$nb"
        done

    - name: Run tests
      run: |
        pip install pytest
        pytest || echo "Tests failed but workflow continues"
